AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 200
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreNotImplementedMethods: true
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
