#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/cli"

config = MicroManager::Config.new
persistence = MicroManager::Persistence.new(config)
schedule = persistence.recover || MicroManager::Schedule.new

command = MicroManager::CLI::CommandBuilder.new.build(ARGV)
result = command.run(schedule: schedule)
print result.render

persistence.save(schedule)
