name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Install gems
      run: |
        gem install bundler -v 2.2.3
        bundle install
    - name: Run Rubocop
      run: bundle exec rubocop
    - name: Run tests
      run: |
        bundle exec rspec
